name: flutter_localization_flappy_csv
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter
  flappy_translator: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true